apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
  namespace: system
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      containers:
      - name: autoscaler
        image: quay.io/openai/kubernetes-ec2-autoscaler
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: aws-secret-access-key
        - name: SLACK_HOOK
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: slack-hook
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: kubernetes.default
        command:
            - python
            - main.py
            - --regions
            - us-west-2,us-east-1,us-west-1
            - --cluster-name
            - openai-kubernetes
            - -vvv
        imagePullPolicy: Always
      restartPolicy: Always
